# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCulture',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleForeign',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleHuman',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleJoke',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLiterature',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleNews',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhilosophy',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticlePhoto',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('content_type', models.IntegerField()),
                ('article_type', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('sub_content', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover_url', models.CharField(max_length=100)),
                ('content_url', models.CharField(max_length=200)),
                ('read_count', models.IntegerField()),
                ('collect_count', models.IntegerField()),
                ('share_count', models.IntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('collect_type', models.IntegerField()),
                ('collect_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TextAndImage',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('articleId', models.IntegerField()),
                ('text', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(serialize=False, primary_key=True, auto_created=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('pw_md5', models.CharField(max_length=70)),
                ('wx_no', models.CharField(max_length=100)),
                ('wb_no', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='textandimage',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='collect',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlephoto',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlephilosophy',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlenews',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articleliterature',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlejoke',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlehuman',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articlehistory',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articleforeign',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
        migrations.AddField(
            model_name='articleculture',
            name='user_id',
            field=models.ForeignKey(to='Background.User'),
        ),
    ]
